### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by nzpopa** [leeoniya/uFuzzy#1]
It would be cool to wrap this into a vscode extension. I'd definitely use it

**Comment by leeoniya** [comment]
vscode already has a pretty effective fuzzy match (at least for Ctrl+P file searching), what am i missing here?

**Comment by leeoniya** [comment]
i have no plans to work on third-party wrappers/integration outside the core, but if someone wants to build on top of it, then i can link any related projects from the readme.
