### ISSUE TITLE
should `intraMode: 1` allow errors in the last char?

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uFuzzy#11]
currently it doesn't, so `bleu` will not match `blue`

https://github.com/leeoniya/uFuzzy/blob/15b72df13b93d9ff6e00f026279c39934ff59352/src/uFuzzy.js#L146

**Comment by Fannon** [comment]
To me it sounds reasonable, probably what you expect when allowing 1 error that there is not distinction if it is in between or at the end of the string.

**Comment by leeoniya** [comment]
should work now. i also tightened some rules for terms < 5 chars. e.g. you _really_ don't want to match every term that ends with `ble` when searching `blue` due to allowing single deletion of "u".

if you actually want to do this, there is now `intraSlice` and `intraRules` options that allows for tweaking per-term in the needle and exactly what is required. the defaults are currently set to `intraSlice: [1, Infinty]` (allows errors in all but first char) and `intraRules` which limits what types of errors are tolerated in short terms:

https://github.com/leeoniya/uFuzzy/blob/4b1249a38715e7d7888894609bd5de5c6f3408cc/src/uFuzzy.js#L113-L153
