### ISSUE TITLE
Polyfill prototype.at

### ISSUE THREAD

**Issue by l2aelba** [leeoniya/uFuzzy#12]
In my case, I using uFuzzy in React Native (Android)

When we search the long char, we got errors like:

```
p.at is not a function. (In 'p.at(-1)', 'p.at' is undefined)
```

I'm not sure this is a good idea to add polyfill something like

```js
if (!String.prototype.at) {
  String.prototype.at = function (n) {
    // ToInteger() abstract op
    n = Math.trunc(n) || 0;
    // Allow negative indexing from the end
    if (n < 0) n += this.length;
    // OOB access is guaranteed to return undefined
    if (n < 0 || n >= this.length) return undefined;
    // Otherwise, this is just normal property access
    return this[n];
  };
}
```

Any suggestion? thanks.

**Comment by leeoniya** [comment]
i think it's easier to just avoid using it.

https://github.com/leeoniya/uFuzzy/blob/15b72df13b93d9ff6e00f026279c39934ff59352/src/uFuzzy.js#L144

```js
 let rgtChar = p[plen-1]; 
```

**Comment by l2aelba** [comment]
@leeoniya Are going to change and release this?
