### ISSUE TITLE
Ignore a part of the needle?

### ISSUE THREAD

**Issue by Freddy03h** [leeoniya/uFuzzy#13]
Hello, thank you for your library, I'm about to switch from Fuse.js!

I just found a use case that can be problematic for some search logic : in a needle with many part, and many part matches results, but if one part only doesn't match, the result is entirely excluded.

Example with needle `super mario 64` and options `intraMode: 1, intraSub: 1, intraTrn: 1, intraDel: 1, intraIns: 1` on this data set :
https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&intraIns=1&intraMode=1&search=super%20mario%2064

I think all "super mario" results should appear, but it doesn't pass the `filter` function at all.

Is there a configuration that can handle this use case that I missed? Thank's!

**Comment by leeoniya** [comment]
the only way to do this is to pre-process the needle to exclude what you don't consider to be important.

it's not possible to do this automatically and still get good results. what if we ignore `64` _and_ `mario`? would you want all the matches for `super`? probably not!

i think what you want is something like removing "stop words" from the needle, and in this case numbers would be included in your stop words to be removed before matching.

**Comment by Freddy03h** [comment]
Hi! thank you for your fast answer!

I don't think it's a stop words problem because the issue is the same with non-stop words, for example `super mario galaxy` have the same result.

Is there no way to create kind of rule in the `filter` to pass if half the words are founds in the sentence?

For example in my product I have `Super Mario - Manga adventures` which is not found using `Super Mario Manga adventures t4` needle. And I don't think this use case is for "heavier full-text doc search", it's still about searching in title only.

I can pre-process the needle for case with sentence with a pattern that came from an api.

But this use case exist also for needle that came from real world users : like the way it's common for users to make typo and fuzzy search to handle error in a term of the search phrase., users also sometimes provide a useless term in the sentence that it's preferable to ignore.
For example, a user isn't always aware about the exact name of what is looking for, and he's used to use real search engine so he can type a sentence like `super mario wii` and I think that not displaying any result at all give him the message that there is no `super mario` entries.

I know that a fuzz search with weight result for each terms is an other level an you want to keep it simple, but like the way uFuzzy handle SingleError as an heuristics that provide good results, is there really any way to ignore one word or two in the sentence?

From a user perspective, having results with `suepr mairo` and not with `super mario wii` doesn't make sense.

Thank you.

**Comment by leeoniya** [comment]
> he's used to use real search engine

which are all document search engines, with enormous indexes :)

> `super mario wii`

if you type this, you will get all super mario results until you start typing `wii`. this would be obvious and not confusing in a live filter. as-you-type situation. but can be a problem if you copy/paste.

> is there really any no way to ignore one word or two in the sentence?

not in the core, no.

you can run additional searches for needles with terms omitted and combine the results at the end. it would work the same way as outOfOrder is implemented inside `compare.html`. if you have a large haystack this can get quite slow looking for each combination of letter omissions, term omissions, and term reorderings.

for large fuziness support you need to keep an index to maintain performance, which is what doc search libs do.
