### ISSUE TITLE
Is there an example of stripping diacritics?

### ISSUE THREAD

**Issue by rap2hpoutre** [leeoniya/uFuzzy#22]
In french, accent and diacritics may or may not be used by users. It should be considered. Is there an option for this?

**Comment by leeoniya** [comment]
there's a static utility function `uFuzzy.latinize(stringsArr)` that you can use to pre-process your haystack once before doing any searches, and preprocess your needle on each search.

**Comment by leeoniya** [comment]
i should probably have it accept a single string as well so there's no additional ceremony of wrapping the needle in an array and unwrapping the result.

**Comment by leeoniya** [comment]
that's also likely to be 10x slower, but def an viable option.
