### ISSUE TITLE
Matching words that include punctuation

### ISSUE THREAD

**Issue by darrylnoakes** [leeoniya/uFuzzy#23]
Is there a recommended way to fuzzy match words that include punctuation?

For example, I want "everybodys" to match "everybody's".
I have set the `intra*` options and included an apostrophe in `intraChars` (`[a-z\\d']`) and `interSplit` (`[^A-Za-z0-9']+`), which seems to give the desired behavior.
I have also used a tweaked `intraRules` function to allow shorter terms to have a missing char so that "its" will match "it's". It required some TypeScript finagling because `intraIns` is a `number` in the options but the return must have it as `0 | 1`...

So it pretty much works, but I want to know if you have any recommendations for this scenario.

**Comment by leeoniya** [comment]
> So it pretty much works, but I want to know if you have any recommendations for this scenario.

what you're doing is the way to do it. `intraIns: 1, intraChars: "[a-z\\d']"`. you don't need to adjust `interSplit` though.

![image](https://user-images.githubusercontent.com/43234/217330787-90b8689b-8880-4606-a172-85b9c3c0ab3e.png)

> I have also used a tweaked `intraRules` function to allow shorter terms to have a missing char so that "its" will match "it's"

ah, maybe that's why you adjusted `interSplit` (so it can be treated as one term). surprised to see someone poking the more advanced (and undocumented!) options for fine-tuning the behavior :trophy: 

> It required some TypeScript finagling because `intraIns` is a `number` in the options but the return must have it as `0 | 1`.

yeah, not sure how to type this better without the typings becoming :exploding_head: :(

**Comment by leeoniya** [comment]
one nice thing you do lose by treating `everybody's` as a single term is error tolerance in `everybody`.

maybe a better option is to just pre-process the needle to remove any occurrences of `'s` and replace all `ys\b` with `y`.

**Comment by leeoniya** [comment]
`'s`, `'ll`, `'d`, `'re`, `'t`, `'m`, `'ve` are really common so it feels silly that uFuzzy splits them off into separate terms. we can probably try a bit harder to avoid the badness when we see them in the needle, which should be more feasible than handling the case when they're absent from the needle, such as `everybodys`

**Comment by leeoniya** [comment]
check out https://github.com/leeoniya/uFuzzy/commit/efe6bdf9593e80b841b454e7a848e9ec27f1b5f7 :)

**Comment by leeoniya** [comment]
check out 67378ad1fbfad10067eb3d34d27e9792e1557559 :)

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&intraIns=1&intraMode=1&search=evrybody%27s

![image](https://user-images.githubusercontent.com/43234/217396178-a0ea6d29-f223-48b8-a710-a88d51869981.png)

**Comment by darrylnoakes** [comment]
Great! That looks like it solves the case of when the apostrophe is included in the search term. Nice to have a proper solution for that that's made by someone smarter than me. 😉

I'll continue using the `intraIns` and `intraChars` config for the case where the apostrophe is omitted.

Overall, I believe that resolves an concerns I had. Thanks again!

**Comment by leeoniya** [comment]
> Searching for "it's" with default interSplit and MultiInsert: 7,556 results (of 161,844)
> Searching for "it's" with default interSplit and SingleError: 7,556 results (of 161,844)

actually, i'm struggling to reproduce these counts with v1.0.2. is this with your custom `intraRules` that has relaxed allowances for short terms?

i assume that the new changes allow you to omit your `intraRules` customization?

**Comment by darrylnoakes** [comment]
> actually, i'm struggling to reproduce these counts with v1.0.2. is this with your custom `intraRules` that has relaxed allowances for short terms?

No, that was the demo as-was, except for maybe changing `intraChars` to include an apostrophe.

> i assume that the new changes allow you to omit your `intraRules` customization?

I'm not sure if I was unclear, but I was using it to allow shorter (3 char instead of 4) terms to have _omitted_ chars, so that "its" (search term) was allowed to match "it's" (result). In the current version of the demo, that behavior would mean that "its a wipe" should match "It's a Wipe!", which it does not.

> can you test it with the latest `main` to make sure it does what you want? i dont want to release something that ends up not fixing anything :). you can change your dependencies to `"@leeoniya/ufuzzy": "leeoniya/uFuzzy#67378ad1fbfad10067eb3d34d27e9792e1557559"` to test using latest github commit.

Sure. The method for using a plain commit is what I was missing. I'll probably get a chance tomorrow.

**Comment by leeoniya** [comment]
8bf4d9cde9d5357fa97f992790636a7877732fe3 adds `'` to the default `intraChars`. i think it makes sense with the other changes here. the commit also makes the contraction regex more conservative to fix searches like `d'angelo`.

in MultiInsert mode, `its a wipe` now works with just the `intraChars: 1` tweak. for SingleError, you'll still need to customize `intraRules` to return `intraChars: 1` for terms < 4 chars.

**Comment by leeoniya** [comment]
great, thanks. i'll get a release out today or tomorrow.
