### ISSUE TITLE
hangs on needles without alphanumerics

### ISSUE THREAD

**Issue by tckmn** [leeoniya/uFuzzy#24]
minimal example:

```js
new uFuzzy({interLft: 1}).search(['a'], '@', true); // hangs
```

it's fine without the `interLft` parameter. in general, the kind of string that hangs it seems to be any string that doesn't have a letter or number, like `'@'`, `'$&@*'`, or `''`.

**Comment by leeoniya** [comment]
hmm, i wonder what the correct fix is here.

i'm tempted to throw an exception if the needle preprocessing results in an empty needle. something like

```js
throw `Needle '${needle}' contained no searchable chars`;
```

here:

https://github.com/leeoniya/uFuzzy/blob/60170b627986a9fca53a5c577d595baf8ab9288b/src/uFuzzy.js#L172
