### ISSUE TITLE
Search returns all items in haystack when second and third character in needle are the same

### ISSUE THREAD

**Issue by GideonRoose** [leeoniya/uFuzzy#27]
## Introduction
We have noticed that the search returns all items in the haystack in their original order when using a needle of 3 characters, from which the second and third character must be the same, regardless of whether it should or should not return any results. The problem seems to be setting the intraMode to SingleError.

## How to reproduce
To be complete, here is my setup:
```
const uf = new uFuzzy({
    intraMode: 1, // SingleError
    intraIns: 1,
    intraDel: 1,
    intraSub: 1,
    intraTrn: 1
});

const haystack = [...];
const outOfOrder = true;
const needle = "qqq"; // or "aqq", "bff", "dcc", etc.

uf.search(haystack, needle, outOfOrder);
```

## Example
https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=qqq&intraIns=1&intraMode=1&outOfOrder=1

If you search for "qq", you will see no results (which is expected). But when searching for "qqq" we get all results in their original order.

**Comment by leeoniya** [comment]
well, that's not ideal 😅

will investigate today, thanks for the repro!

**Comment by leeoniya** [comment]
should be fixed now.
