### ISSUE TITLE
Add more docs for how to add character sets to search?

### ISSUE THREAD

**Issue by jd1378** [leeoniya/uFuzzy#32]
currently it's not really clear how to add support for other languages like Arabic for example
would you mind adding these info as examples to the docs ?

**Comment by leeoniya** [comment]
what part do you find unclear about https://github.com/leeoniya/uFuzzy#charsets-alphabets-diacritics?

**Comment by jd1378** [comment]
what are `various uFuzzy opts e.g.` and how to use them

**Comment by leeoniya** [comment]
all of the regexp opts and their purpose is described in https://github.com/leeoniya/uFuzzy/blob/main/dist/uFuzzy.d.ts#L100

since i have no knowledge of Arabic, its charset, or sentence structure, i cannot provide any guidance for what the regexps for it should look like.

**Comment by jd1378** [comment]
I look at it and don't understand anything :D 

let's say arabic charset is `[\u0621-\u064A]` (i'm not sure, just assuming this is correct to continue)

How can I add this to the character set that is already there for english?
can you provide an example ? it would be very helpful

**Comment by jd1378** [comment]
using the following seems to work (probably not ideal):
```ts
const uFuzzyOptions = {
      interSplit: "[^\\p{L}\\p{N}']+",
      intraSplit: '[\\p{L}][\\p{L}]',
      intraBound: '[\\p{L}][\\p{N}]|[\\p{N}][\\p{L}]|[\\p{L}][\\p{L}]|[\\p{L}]',
      intraChars: "[\\p{L}\\p{N}']",
      intraContr: "'[\\p{L}]{1,2}\\b",
      unicode: true,
    }
```

**Comment by jd1378** [comment]
it got a lot better by aligning it to what is already there:
```ts
const uFuzzyOptions = {
      interSplit: "[^\\p{L}\\p{N}']+",
      intraSplit: '[\\p{Ll}][\\p{Lu}]',
      intraBound: '[\\p{L}][\\p{N}]|[\\p{N}][\\p{L}]|[\\p{Ll}][\\p{Lu}]',
      intraChars: "[\\p{L}\\p{N}']",
      intraContr: "'[\\p{L}]{1,2}\\b",
      unicode: true,
}
```
I'm satisfied with the results

I hope this helps anyone that comes to look at it later :)

**Comment by leeoniya** [comment]
awrsome!

it looks like your version doesnt include upper/lower and alpha/num boundaries in the splits, so would treat SuperMan as one term. i wonder if we can preserve that feature with the universal variant. if so, maybe it should become the default. i'll run it through the benchmark today as well.

**Comment by jd1378** [comment]
the only concern I have, which I didn't find answer for, is that how is the support for `\p{L}` in browsers
I saw it in some proposal from around 6-7 years ago, which I guess should have quite good support now, but it would be reassuring to know the actual support for it.

and I'm glad I could find an answer that could possibly be the new default! it made me happy :)

also what is NEGS_RE in the source code? should be turned into an option ?

**Comment by leeoniya** [comment]
i'm hoping this means unicode features coverage is universal / same these days: https://caniuse.com/mdn-javascript_builtins_regexp_unicode

> also what is NEGS_RE in the source code? should be turned into an option ?

it plucks out exclusion terms for separate processing, e.g `-bar` in `foo -bar`. not sure it should be an option if it can be constructed from the already-provided intraChars.

**Comment by jd1378** [comment]
> i'm hoping this means unicode features coverage is universal / same these days: https://caniuse.com/mdn-javascript_builtins_regexp_unicode 

That coverage great imo, and thanks for the link (I had tried but couldn't find it there)

>it plucks out exclusion terms for separate processing, e.g -bar in foo -bar. not sure it should be an option if it can be constructed from the already-provided intraChars.

ok, thanks for explaining

I hope performance of it is still good ! looking forward to the benchmarks

**Comment by jd1378** [comment]
I'm glad I could be of help

thanks for the performance comparison
but even 4x slower is a win for me compared to Fuse.js (I was using in some other project)
