### ISSUE TITLE
Limit results?

### ISSUE THREAD

**Issue by howesteve** [leeoniya/uFuzzy#33]
Hi,

Nice project, thanks. Much better than alternatives I tried. Opening an issue here, but's more of a question.

However, I'm missing a way to limit results. Of course I know I can ```[].slice()``` the results, but I mean some way to return earlier from the ```uFuzzy.filter()``` call once the limit has been reached.

Thanks

**Comment by leeoniya** [comment]
there's no way to early exit, but also i don't think it makes sense for search libs that aim to show you the highest quality matches first.

the only reason to do this would be maybe some kind of optimization in speed at the huge drop in quality of first-page matches.

is there a specific perf problem you're trying to work around with this?

**Comment by leeoniya** [comment]
as thr readme says, uFuzzy doesnt have a "score". it collects stats (uf.info) about each match and then uses an array sort to order by those stats.

> 2000 blog articles

this definitely sounds like a use case for a fulltext search in a backend database where term frequency is taken into account for ranking as well as boosting for terms occuring in the heading or url slug. if you want that to handle spelling errors you could pre-process the raw query to auto-correct, for example.

**Comment by howesteve** [comment]
Thanks, I actually agree. Any FTS suggestions? I didn't like those I tried. Maybe I should start over...

**Comment by leeoniya** [comment]
if the built-in FTS in SQLite/MySQL/Postgres is not sufficient, maybe:

https://pagefind.app/
https://github.com/meilisearch/meilisearch
https://typesense.org/

**Comment by howesteve** [comment]
> if the built-in FTS in SQLite/MySQL/Postgres is not sufficient, maybe:
> 
> https://pagefind.app/ https://github.com/meilisearch/meilisearch https://typesense.org/
I mean, client-side. I know meilisearch , zinc serach - these are great, but it must be client-side.

**Comment by leeoniya** [comment]
not sure about the wisdom behind downloading 2000 full articles to the client just to be able to search them and probably only read a few. something that allows building and downloading only a compressed index rather than full content would be ideal. is this not what Pagefind does?

> After indexing, Pagefind adds a static search bundle to your built files, which exposes a JavaScript search API that can be used anywhere on your site. Pagefind also provides a prebuilt UI that can be used with no configuration (you can see the prebuilt UI at the top of this page).

anyways, all these should be better than Fuse.js, but i have no specific experience with them for your use case:

https://github.com/oramasearch/orama (formerly Lyra)
https://github.com/nextapps-de/flexsearch
https://lucaong.github.io/minisearch/
https://github.com/localvoid/ndx

you can also try to compile meilisearch or typesense to WASM and go that route.

**Comment by howesteve** [comment]
Thanks again for the reply. This particular application includes a medical articles encyclopedia. Articles must be available and searchable offline; they are .md files with 2 to 20Kb. Gzipped, it's under 8mb. It's downloaded on first user access, and indexed on the browser. However, indexing can easily eat heap memory pretty fast, so I cannot use any indexer. Specially on users coming from mobile. 
Maybe someday dataset size gets larger and I end up needed indexedb support, but it still fits entirely in memory.

I had seen those alternatives expect for Pagefind and was not attracted to any of them: some have crazy developers (I'm sure you can imagine which), others no multilang support, or memory hoggers, and so on.
I'm going to try Pagefind, thank you again.
