### ISSUE TITLE
Add SingleError mode option to uf.search

### ISSUE THREAD

**Issue by mark-conway** [leeoniya/uFuzzy#34]
Currently, we can pass other options to uf.search. It would be great to allow other modes. Thank you.

**Comment by leeoniya** [comment]
architecturally it doesn't make sense. `uf.search` is a wrapper around the core API (you could implement it mostly outside of uFuzzy), so it only accepts non-core options. `intraMode` is core option that is immutable after init.

you can/should write a wrapper that simply re-inits a new uFuzzy instance when you change modes.

**Comment by mark-conway** [comment]
Ah, makes sense. Thank you!
