### ISSUE TITLE
æøå

### ISSUE THREAD

**Issue by aslak01** [leeoniya/uFuzzy#35]
Hey,

I want to use this for a project, but I need to support the Norwegian letters æøå as a part of the search query/results, but I haven't been able to work out how to do it. As is, they are just ignored, which doesn't work for me as I need to be able to find "Ål" for example, and I don't want to instruct users that need that string to use quotation marks. I don't mind making a private fork if there's concern about feature creep or something,

**Comment by leeoniya** [comment]
have you read https://github.com/leeoniya/uFuzzy#charsets-alphabets-diacritics ?

**Comment by aslak01** [comment]
To be honest, I ran into this limitation a month or two ago, and didn't re-read the readme before posting this. I read and messed around with those settings mentioned in that part then, but there appears to have been some updates since that time. I think I just need to define the search regex as `[a-zA-ZæøåÆØÅ]`, but I wasn't able to make it work last time. I'll mess around with it again on tuesday.

**Comment by leeoniya** [comment]
yep, it's similar to Latin + Cyrillic. you'll have to update all the regexp opts shown in that readme section for the generalized unicode case, minus the unicode flag.

**Comment by leeoniya** [comment]
added to Norwegian example to readme

**Comment by aslak01** [comment]
Thank you!

**Comment by leeoniya** [comment]
@aslak01 check out https://github.com/leeoniya/uFuzzy/issues/36. it adds much cleaner `{letters: "a-zæøå"}` API for this.
