### ISSUE TITLE
Single quote character in haystack causes missing matches and breaks sorting

### ISSUE THREAD

**Issue by arctica** [leeoniya/uFuzzy#40]
I noticed that if an entry in the haystack contains a single quote character `'` and one uses `interLft: 2` (or 1), the `idxs.length` and `order.length` of the result of search() do not match up. The `order` array will have less items than `idxs`. This results in missing matches and the ordering being broken.

Reproduce with:

```js
let haystack = [
  "Foo'xy1234567890",
  "xy1",
  "xy123",
];

let needle = "xy";

let opts = {
  intraMode: 0,
  interLft:  2,

  sort: (info, haystack, needle) => {
    return info.idx.map((v, i) => i).sort((a, b) => haystack[info.idx[a]].length - haystack[info.idx[b]].length);
  }
};

let uf = new uFuzzy(opts);

let [idxs, info, order] = uf.search(haystack, needle, true, 1e5);

console.log(idxs.length, order.length, order.map(i => haystack[idxs[i]]));
```

Which will output

```
3, 2, ["Foo'xy1234567890", "xy1"]
```

Note how "xy123" is missing from the `order` results and the long string comes before the short one even though we are sorting by shortest string.

If we instead change the single quote in `Foo'xy1234567890` to some other special character like a dot `Foo.xy1234567890` we will see this output instead:

```
3, 3, ["xy1", "xy123", "Foo.xy1234567890"]
```

All results are returned and the sorting works as expected.

This does not happen if you use `interLft: 0`. I was not able to find other special characters that behave in the same broken way.

**Comment by leeoniya** [comment]
> I was not able to find other special characters that behave in the same broken way.

there is some special treatment for `'` to avoid splitting a needle like `d'angelo` into two terms `d angelo` or `where's waldo` into `where s waldo`, since `d` and `s` should not be treated as separate terms.

you can avoid this special behavior by adjusting the regexps and `intraContr`

**Comment by arctica** [comment]
Thank you for the explanation and pointing to a workaround.

But even considering these facts shouldn't the "idxs" and "order" arrays always have the same length? Note how instead of the entry containting the `'`, another entry will be omitted from the matches. On the other hand the entry with the `'` that should not be in the matches is there. Oh and the sort order being wrong :)

Unless I mixed something up with the array indices?

**Comment by leeoniya** [comment]
yeah, i'll check it out. probably bug.

**Comment by leeoniya** [comment]
ok, not a bug.

`idxs` is only relevant  when `info` and `order` are `null`. once you have those, you should rely on the `info.idx` array, and `order` being a reference into that. this is because the "info" pass does additional post-filtering. this is mentioned in the example code comments: https://github.com/leeoniya/uFuzzy#example
