### ISSUE TITLE
Providing special characters as the needle causes errors

### ISSUE THREAD

**Issue by mririgoyen** [leeoniya/uFuzzy#42]
When feeding in a special character, such as `!`, as the needle. An error is logged to the console. In cases where the logic isn't in a try/catch, it can cause an application crash.

**Reproduction example:**
```
const uf = new uFuzzy({});

const needle = ' '; // Change this to other characters, such as ~, !, #, etc.

const haystack = ['~', 'test', 'testing', 'pretest', 'posttest', 'fuzzy'];

const idxs = uf.filter(haystack, needle) || [];
const info = uf.info(idxs, haystack, needle);
const order = uf.sort(info, haystack, needle);
console.log(order);
```

> ufuzzy.js:192 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.info (ufuzzy.js:192:26)

Codepen example of the failue: https://codepen.io/mririgoyen/pen/WNLwjJQ (Be sure to open the browser's console)

**Comment by leeoniya** [comment]
yeah, the needle may become empty after all non-searchable chars are removed from it.

there's a codepath for this in the `.search()` API:

https://github.com/leeoniya/uFuzzy#integrated-search

https://github.com/leeoniya/uFuzzy/blob/9486cf58cd937bc15082de217febfbf793bd589a/src/uFuzzy.js#L709-L713

**Comment by mririgoyen** [comment]
I believe when you first suggested the library for us over at Pictogrammers, the way we have it implemented was how you suggested we do it. Glad to see there is an easier to use API now. I'll try to get to updating our stuff in the next few evenings.
