### ISSUE TITLE
Should this return info?

### ISSUE THREAD

**Issue by mosnicholas** [leeoniya/uFuzzy#44]
Question on usage -- should this query return all the Call of Duty ... queries? Feels like that should fall in the `intraSub: 1` section?

<img width="1296" alt="Screenshot 2023-09-20 at 9 14 28 PM" src="https://github.com/leeoniya/uFuzzy/assets/3606778/ac6b0990-b0e3-4868-96b0-c20edb050df9">

**Comment by leeoniya** [comment]
although...that doesnt appear to be working: https://jsfiddle.net/2fpw9hvk/

:thinking:

**Comment by leeoniya** [comment]
i'm rather hesitant to adding even more magic, such as relaxing the guards when you have multiple terms in the needle, etc. i think just letting people tweak `intraRules` to their liking is sufficient and straightforward.
