### ISSUE TITLE
Thank god for your library

### ISSUE THREAD

**Issue by 9mm** [leeoniya/uFuzzy#49]
THANK YOU

I have such a long painful history with fuse.js, i eventually just tried it again and remember why its just the worst yet somehow the most popular. 

Your library is freaking awesome, just wanted to say thanks

**Comment by leeoniya** [comment]
:heart: 

glad someone likes it :)

i dont tend to write libs with the friendliest APIs, so i'm always amused when people actually manage to use them with any amount of success :)
