### ISSUE TITLE
How to tweak handling of spaces?

### ISSUE THREAD

**Issue by tomas** [leeoniya/uFuzzy#5]
Hi, your library looks awesome! Kudos to you.

I was trying the demo, but I couldn't find a way to tell uFuzzy to include results that contain spaces in between the search query. I want to get results like "Super Markup Man" or "Super Mario" when querying for "superma" (just remove the space between `super` and `ma` in the example query).

![image](https://user-images.githubusercontent.com/10574/194148524-764c9bf8-6099-449d-bf98-26396ac0b9c7.png)

Is this possible?

**Comment by leeoniya** [comment]
thanks!

- `intraIns` controls how many extra chars are allowed between each char within a term, so you can set it to some big number, or `Infinity`. deleting the limit in the demo sets it to `Infinity`
- `intraChars` controls which chars can occur between chars within a term, so you can add a space to the regex: `[a-z\d ]`

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=superma&intraIns=inf&intraChars=[a-z\d%20]

depending on your corpus, this may or may not be great. effectively it treats the whole thing as one big term with a bunch of junk in between. you'll also loose the benefit boosting multiple terms that fall at expected bounds (whitespace, punct, etc). you can do a bit better by swapping out the sorting function for one that prioritizes other aspects of matches to maybe get better ordering than you get in the demo.

there is currently no counter in the `info` object for how many matched chars landed on word boundaries (only full terms). i'll see if this can be added without too much overhead, which should help with what a custom sorting function can consider.

**Comment by leeoniya** [comment]
if you don't allow `intraIns` to be arbitrarily large, you get much better results:

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=superma&intraIns=1&intraChars=%5Ba-z%5Cd%20%5D

![image](https://user-images.githubusercontent.com/43234/194163856-633a14d0-5502-45de-95bf-4166b1eece56.png)

**Comment by tomas** [comment]
I see. `intraIns: 1` plus adding a space to the regex did the trick. Thanks for the quick response!

**Comment by arctica** [comment]
@leeoniya It seems like in `intraMode=1` the tollerance to spaces does not work.
Searching for `supermariobros` does not find anything when SingleError mode is selected.

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=1&intraChars=[a-z\d%20]
vs
https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=0&intraChars=[a-z\d%20]

**Comment by yan42685** [comment]
> @leeoniya It seems like in `intraMode=1` the tollerance to spaces does not work. Searching for `supermariobros` does not find anything when SingleError mode is selected.
> 
> [https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=1&intraChars=[a-z\d%20]](https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=1&intraChars=%5Ba-z%5Cd%20%5D) vs [https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=0&intraChars=[a-z\d%20]](https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy&search=supermariobros&intraIns=1&intraMode=0&intraChars=%5Ba-z%5Cd%20%5D)

Same here. And thanks for your info which helps me find the reason that causes the unexpected results :)
