### ISSUE TITLE
I made a thing with uFuzzy :)

### ISSUE THREAD

**Issue by KraXen72** [leeoniya/uFuzzy#55]
Just wanted to show that i've made a thing using this awesome library! It has been a joy! Feel free to give feedback if something about the uFuzzy logic could be improved.

https://github.com/KraXen72/obsidian-emoji-autocomplete

Custom sorting algorithm:
https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/master/src%2Fmain.ts#L204

Thanks for making such a good fuzzy :))

**Comment by leeoniya** [comment]
nice :)

i probably wont have time to review all the logic, but from initial look, some of the sorting can be optimized. sort functions can run _a lot_ for big lists, so things like linear-scan checks into arrays will get expensive:

https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/612c0f39e566a285ef4abb8cfe33ebd5ccacc5ca/src/main.ts#L213-L214

using `!` to coerce and check for null or undefined is less efficient than `== null`, so maybe more optimization there.

https://github.com/KraXen72/obsidian-emoji-autocomplete/blob/612c0f39e566a285ef4abb8cfe33ebd5ccacc5ca/src/main.ts#L221-L222

> Thanks for making such a good fuzzy :))

glad you like it :)

**Comment by KraXen72** [comment]
thanks, will take a look at the optimizations you suggested. my use case is a 1400-2500 long list, and i am getting <4ms, top 1% longest <12ms times, which is very acceptable.

**Comment by KraXen72** [comment]
is using array.prototype.indexOf to check presence any faster? or what would you suggest for checving if an item is in the history? Prehaps a Map or Set? thanks

**Comment by leeoniya** [comment]
indexOf might be a bit faster than includes, but Set is the way to go.
