### ISSUE TITLE
Question about the example in the README

### ISSUE THREAD

**Issue by nicolaibach** [leeoniya/uFuzzy#6]
hi,
I replicated the [example](https://github.com/leeoniya/uFuzzy#example) from the readme to test it with some custom data and I think there's a mistake in it. 
At the end of the example it logs the data from the `haystack` using `i` directly:

```js
// render pre-filtered but unordered matches
for (let i = 0; i < idxs.length; i++) {
  console.log(haystack[i]);
}
```

Shouldn't this use `idxs[i]` to reference the matches?

```js
for (let i = 0; i < idxs.length; i++) {
  console.log(haystack[idxs[i]]);
}
```

Thank you!

**Comment by leeoniya** [comment]
oops! yep, thanks!
