### ISSUE TITLE
Emoji matching doesn't work on Safari 

### ISSUE THREAD

**Issue by ocavue** [leeoniya/uFuzzy#63]
Open https://stackblitz.com/edit/vitejs-vite-ykkskh in Safari / Chrome / Firefox

Both Chrome and Firefox can show "result: 🍎" as expected, but Safari shows empty result.

After some digging, I found that Safari output different result for the following JS code:

```js
const s = "🍎".replace(/^[^\p{Emoji}]+|[^\p{Emoji}]+$/u, "")

for (let i = 0; i < s.length; i++) {
  console.log(s.codePointAt(i))
}
```

```
// Safari output:
55356

// Chrome and Firefox output:
127822 
57166 
```

It seems that this is a Safari bug. I will try to find or create a issue ticket to the WebKit team.

Update: I created a WebKit ticket https://bugs.webkit.org/show_bug.cgi?id=272546

**Comment by karlcow** [comment]
So I could not reproduce in STP 192.

**Comment by karlcow** [comment]
@ocavue which versions of Safari did you use? which device too?

**Comment by karlcow** [comment]
![Screenshot 2024-04-12 at 14 07 14](https://github.com/leeoniya/uFuzzy/assets/505230/29d57771-837e-4acf-9cb7-0c97adcb6ebe) It may have been fixed recently.

**Comment by ocavue** [comment]
<img width="1470" alt="image" src="https://github.com/leeoniya/uFuzzy/assets/24715727/9de84fb6-f346-4027-b7c5-0e0b1910398e">

Yes you're correct. This issue doesn't occur on STP 192. Sorry for the disturbance, I should have tried the latest STP from the beginning.
