### ISSUE TITLE
Using {unicode: true}

### ISSUE THREAD

**Issue by tipsy** [leeoniya/uFuzzy#66]
First of all, thanks for this project @leeoniya!

I am having an issue with `{unicode: true}`, I think. If I use `{ alpha: "a-zæøå" }`, I can search for `æøå` without issue. From reading the docs, it seems to me that `{unicode: true}` is a slower but more general version of this, but I am not getting any results with `{unicode: true}`, instead I am getting a null which crashes the rest of my code:

### `{ alpha: "a-zæøå" }`
![image](https://github.com/leeoniya/uFuzzy/assets/1521451/7c52a952-60da-4986-8b38-84bd389658fe)

###  `{unicode: true}`.
![image](https://github.com/leeoniya/uFuzzy/assets/1521451/80a4461b-24fa-49a2-a236-92500f7d747f)

**Comment by leeoniya** [comment]
`unicode: true` by itself is not enough, you have to set the other options with it, as shown in the docs.

**Comment by tipsy** [comment]
Thanks @leeoniya - seems you have to do 

```js
// Unicode / universal (50%-75% slower)
let opts = {
  unicode: true,
  interSplit: "[^\\p{L}\\d']+",
  intraSplit: "\\p{Ll}\\p{Lu}",
  intraBound: "\\p{L}\\d|\\d\\p{L}|\\p{Ll}\\p{Lu}",
  intraChars: "[\\p{L}\\d']",
  intraContr: "'\\p{L}{1,2}\\b",
};
```
