### ISSUE TITLE
node_modules/@leeoniya/ufuzzy/dist/uFuzzy"' has no default export.

### ISSUE THREAD

**Issue by zhihengGet** [leeoniya/uFuzzy#70]
node_modules/@leeoniya/ufuzzy/dist/uFuzzy"' has no default export.  code run just ts warn

when i use it in sveltekit with 'import uFuzzy from 'uFuzzy'

**Comment by leeoniya** [comment]
i think you gotta set one of these `tsconfig` options to true:

```
    // "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
```

see: https://www.typescriptlang.org/tsconfig/#Interop_Constraints_6252

i'm not super sure what changes i need to do to [uFuzzy.d.ts](https://github.com/leeoniya/uFuzzy/blob/main/dist/uFuzzy.d.ts) to make it properly recognize a default export. my understanding is that this should work, but apparently it does not?

https://github.com/leeoniya/uFuzzy/blob/de016fd0c3b849d305b57828844f2e960a0a7c6c/dist/uFuzzy.d.ts#L56

**Comment by leeoniya** [comment]
if you don't want to modify your `tsconfig`...

instead of this:

```ts
import uFuzzy from '@leeoniya/ufuzzy';
```

you can use this:

```ts
import * as uFuzzy2 from '@leeoniya/ufuzzy';
```

**Comment by leeoniya** [comment]
ok, it looks like changing from `export = uFuzzy;` to `export default uFuzzy;` fixes this.
